version: '3.9'

services:
  # bitcoin:
  #   image: jamesob/bitcoin-opvault-inq
  #   # If you want to build bitcoind yourself, or are having permission problems, 
  #   # uncomment below.
  #   #
  #   # build: 
  #   #   context: ./
  #   #   dockerfile: bitcoin.Dockerfile
  #   #   args:
  #   #     - UID
  #   #     - GID
  #   volumes:
  #     - ./bitcoin-datadir:/home/user/.bitcoin

  # Mutinynet
  bitcoin:
    build: 
      context: ./
      dockerfile: Dockerfile.mutinynet
    volumes:
      - ./bitcoin-datadir:/home/user/.bitcoin

  demo:
    build:
      context: ./
      args:
        - UID
        - GID
    volumes:
      - ./:/home/user/app
      # Share bitcoin's datadir so that we can make RPC calls with cookie credentials.
      - ./bitcoin-datadir:/home/user/.bitcoin
    links:
      - bitcoin
